language: python
env:
  matrix:
    - DJANGO_PACKAGE="Django>=1.6,<1.7"
    - DJANGO_PACKAGE="Django>=1.7,<1.8"
    - DJANGO_PACKAGE="Django>=1.8,<1.9"
install:
  - sudo apt-get install swig
  - pip install --upgrade pip
  - pip install -q $DJANGO_PACKAGE 
  - pip install -e .
  - pip install -r ./testproj/requirements.txt
  - pip freeze
script: ./testproj/manage.py test testproj
